from bosk.block.zoo.multi_grained_scanning.multi_grained_scanning_1d import MultiGrainedScanning1DBlock
from bosk.block.zoo.multi_grained_scanning.multi_grained_scanning_2d import MultiGrainedScanning2DBlock
